// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function CancelOperation():Promise<void>;

export function CheckFinderActionsInstalled():Promise<boolean>;

export function ClearRecentArchives():Promise<void>;

export function CompressArchive(arg1:engine.CompressOptions):Promise<void>;

export function ExtractArchive(arg1:engine.ExtractOptions):Promise<void>;

export function GetRecentArchives():Promise<Array<string>>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function InstallFinderActions():Promise<string>;

export function OpenArchive(arg1:string,arg2:string):Promise<engine.ArchiveInfo>;

export function OpenFolder(arg1:string):Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;

export function SelectArchiveFile():Promise<string>;

export function SelectFilesToCompress():Promise<Array<string>>;

export function SelectFolderToCompress():Promise<string>;

export function SelectOutputDirectory(arg1:string):Promise<string>;

export function SelectSaveArchivePath(arg1:string,arg2:string):Promise<string>;

export function TestArchive(arg1:string,arg2:string):Promise<engine.TestResult>;

export function UninstallFinderActions():Promise<string>;
