// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelOperation() {
  return window['go']['main']['App']['CancelOperation']();
}

export function CheckFinderActionsInstalled() {
  return window['go']['main']['App']['CheckFinderActionsInstalled']();
}

export function ClearRecentArchives() {
  return window['go']['main']['App']['ClearRecentArchives']();
}

export function CompressArchive(arg1) {
  return window['go']['main']['App']['CompressArchive'](arg1);
}

export function ExtractArchive(arg1) {
  return window['go']['main']['App']['ExtractArchive'](arg1);
}

export function GetRecentArchives() {
  return window['go']['main']['App']['GetRecentArchives']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function InstallFinderActions() {
  return window['go']['main']['App']['InstallFinderActions']();
}

export function OpenArchive(arg1, arg2) {
  return window['go']['main']['App']['OpenArchive'](arg1, arg2);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function SelectArchiveFile() {
  return window['go']['main']['App']['SelectArchiveFile']();
}

export function SelectFilesToCompress() {
  return window['go']['main']['App']['SelectFilesToCompress']();
}

export function SelectFolderToCompress() {
  return window['go']['main']['App']['SelectFolderToCompress']();
}

export function SelectOutputDirectory(arg1) {
  return window['go']['main']['App']['SelectOutputDirectory'](arg1);
}

export function SelectSaveArchivePath(arg1, arg2) {
  return window['go']['main']['App']['SelectSaveArchivePath'](arg1, arg2);
}

export function TestArchive(arg1, arg2) {
  return window['go']['main']['App']['TestArchive'](arg1, arg2);
}

export function UninstallFinderActions() {
  return window['go']['main']['App']['UninstallFinderActions']();
}
